#' The H() function
#'
#' @param nu a neural network of the type generated by create_neural_network()
#'
#' @return integer representing the number of hiddne layers

hid <- function(nu) {
  return(length(nu) - 1)
}

#' The D() function
#'
#' @param nu a neural network of the type generated by create_neural_network()
#'
#' @return integer representing the depth of the neural network

dep <- function(nu) {
  return(length(nu))
}

#' The I() function
#'
#' @param nu a neural network of the type generated by create_neural_network()
#'
#' @return an integer representing the input width of the neural network

inn <- function(nu) {
  return(dim(nu[[1]]$W)[2])
}


#' The O() function
#'
#' @param nu a neural network of the type generated by create_neural_network()
#'
#' @return an integer representing the output width of the neural network

out <- function(nu) {
  return(dim(nu[[length(nu)]]$W)[1])
}


#' The L() function
#'
#' @param nu a neural network of the type generated by create_neural_network()
#'
#' @return a tuple representing the layer architecture of our neural network

lay <- function(nu) {
  layer_architecture <- list()
  for (i in 1:length(nu)) {
    layer_architecture <-
      append(layer_architecture, dim(nu[[i]]$W)[1])
  }
  layer_architecture <- append(inn(nu), layer_architecture)
  return(layer_architecture)
}


#' The P() function
#'
#' @param nu a neural network of the type generated by create_neural_network()
#'
#' @return an integer representing the parameter count of our neural network

param <- function(nu) {
  param_count <- 0
  for (i in 1:length(nu)) {
    param_count <-
      param_count + length(nu[[i]][[1]]) + length(nu[[i]][[2]])
  }
  return(param_count)
}
